// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm_uIOz5hazeW0g_zprKNJdQSzxPm813M',
    appId: '1:41141891810:web:0e6a982b1f19c8697de4bb',
    messagingSenderId: '41141891810',
    projectId: 'steamkids',
    authDomain: 'steamkids.firebaseapp.com',
    storageBucket: 'steamkids.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxS5Yuc6dKKhKa0KKFOLDtnALQOzWzw2w',
    appId: '1:41141891810:android:d1720c23168d32a97de4bb',
    messagingSenderId: '41141891810',
    projectId: 'steamkids',
    storageBucket: 'steamkids.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj5M6wmGRbc4ICv3wMWWKyqzfUFVUxEys',
    appId: '1:41141891810:ios:68c8e949db1c75a47de4bb',
    messagingSenderId: '41141891810',
    projectId: 'steamkids',
    storageBucket: 'steamkids.firebasestorage.app',
    iosBundleId: 'com.example.steamkids',
  );

}